[build]
  publish = "dist/public"
  command = "echo 'Building with functions' && ls -la dist/functions/ && ls -la dist/public/"

[build.environment]
  NODE_VERSION = "20.12.2"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "dist/functions"
  node_bundler = "esbuild"
  
[build.processing]
  skip_processing = false